# Generated by Django 4.2.7 on 2023-12-19 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import validationapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=20, validators=[validationapp.models.validate_plate_number])),
                ('color', models.CharField(max_length=255)),
                ('manufactured_date', models.DateField(validators=[django.db.models.fields.DateField])),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(validators=[validationapp.models.validate_age])),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('@ur\\.ac\\.rw$')])),
                ('phone', models.CharField(default='', max_length=15, validators=[validationapp.models.validate_phone_number])),
                ('reference_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(99), django.core.validators.MaxValueValidator(999)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('plate_number', models.CharField(blank=True, max_length=20, validators=[validationapp.models.validate_plate_number])),
                ('Vehicle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='validationapp.vehicle')),
            ],
        ),
    ]
