# Generated by Django 4.2.7 on 2023-12-20 18:29

from django.db import migrations, models
import validationapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('validationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='Vehicle',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='plate_number',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufactured_date',
            field=models.DateField(validators=[validationapp.models.validate_Mdate]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, validators=[validationapp.models.validate_plate_number]),
        ),
    ]
